### ISSUE TITLE
Comprar billete de avion a turquia

### ISSUE THREAD

**Issue by SanTa45zgz** [UNIZAR-30226-2020-03/prueba#1]

**Comment by Piedrafita** [comment]
Estamos en ello

**Comment by Piedrafita** [comment]
@SanTa45zgz vuelo barato

**Comment by SanTa45zgz** [comment]
@Piedrafita

**Comment by Piedrafita** [comment]
[piedraPaleto.txt](https://github.com/UNIZAR-30226-2020-03/prueba/files/4255653/piedraPaleto.txt)
